---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: waas-operator-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - namespaces
  - persistentvolumeclaims
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - resourcequotas
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - update
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - kubevirt.io
  resources:
  - virtualmachines
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  verbs:
  - create
  - get
  - list
  - update
  - watch
- apiGroups:
  - waas.xorhub.io
  resources:
  - workspaceimages
  - workspacepolicies
  - workspacetemplates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - waas.xorhub.io
  resources:
  - workspaces
  verbs:
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - waas.xorhub.io
  resources:
  - workspaces/status
  verbs:
  - get
  - patch
  - update
