---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: waas-operator-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - kubevirt.io
  resources:
  - virtualmachines
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - waas.xorhub.io
  resources:
  - workspaces
  - workspacetemplates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - waas.xorhub.io
  resources:
  - workspaces/status
  verbs:
  - get
  - patch
  - update
