#!/usr/bin/env -S uv run --script
"""Check the operator's Helm ClusterRole against the generated RBAC.

Usage: check_operator_rbac.py <helm-role-file> <generated-role-file>

helm/waas/templates/operator/roles.yaml is a hand-maintained mirror of
the +kubebuilder:rbac markers (operator/config/rbac/role.yaml,
regenerated by `make manifests`): it exists only so every grant can
carry an inline comment justifying it, which controller-gen's output
cannot. Nothing enforced that mirror, so it silently kept a
workspaceimages/status grant behind after the code path that needed it
was removed. This compares both ClusterRoles as sets of
(apiGroup, resource, verb) triples rather than diffing text: controller-
gen alphabetizes and merges rules (e.g. configmaps+secrets into one
rule) differently from how the Helm file splits them to attach
comments, so a text diff would flag harmless reshuffling as drift.
"""
# Inline metadata (PEP 723): `uv run` resolves pyyaml into an ephemeral
# env on its own — no venv, no `pip install` step, in CI or locally.
# /// script
# dependencies = ["pyyaml==6.0.2"]
# ///
from __future__ import annotations

import re
import sys
from pathlib import Path

import yaml

# Matches a single {{ ... }} or {{- ... -}} template expression,
# non-greedily so back-to-back expressions on one line stay distinct.
_TEMPLATE_EXPR = re.compile(r"\{\{.*?\}\}")


def _load_cluster_role(path: Path) -> dict:
    """Parse the sole ClusterRole document out of a YAML/Helm-template file."""
    # helm/waas/templates/operator/roles.yaml is Go-templated only in
    # metadata/labels ({{ .Release.Name }}, {{- include ... }}); every
    # rules: block is plain YAML. Blanking out template expressions
    # line-wise (instead of running `helm template`) keeps this script
    # dependency-free and immune to values that aren't set yet.
    text = "\n".join(_TEMPLATE_EXPR.sub("x", line) for line in path.read_text().splitlines())
    cluster_roles = [
        doc for doc in yaml.safe_load_all(text) if doc and doc.get("kind") == "ClusterRole"
    ]
    if len(cluster_roles) != 1:
        sys.exit(
            f"{path}: expected exactly one ClusterRole document, found {len(cluster_roles)} "
            "(the file layout changed — update this script's assumptions)"
        )
    return cluster_roles[0]


def _rule_triples(cluster_role: dict) -> set[tuple[str, str, str]]:
    """Flatten a ClusterRole's rules into (apiGroup, resource, verb) triples."""
    triples = set()
    for rule in cluster_role.get("rules", []):
        for group in rule.get("apiGroups", []):
            for resource in rule.get("resources", []):
                for verb in rule.get("verbs", []):
                    triples.add((group, resource, verb))
    return triples


def _format(triple: tuple[str, str, str]) -> str:
    group, resource, verb = triple
    group_display = group if group else '""'
    return f"  - apiGroups: [{group_display}] resources: [{resource}] verbs: [{verb}]"


def main() -> None:
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    helm_path, generated_path = Path(sys.argv[1]), Path(sys.argv[2])

    helm_triples = _rule_triples(_load_cluster_role(helm_path))
    generated_triples = _rule_triples(_load_cluster_role(generated_path))

    missing = generated_triples - helm_triples  # generated grants the Helm role lacks
    extra = helm_triples - generated_triples  # Helm grants no +kubebuilder:rbac marker produces

    if not missing and not extra:
        print(f"OK: {helm_path} matches {generated_path} ({len(helm_triples)} grants).")
        return

    report = [f"operator ClusterRole drift between {helm_path} and {generated_path}."]
    if missing:
        report.append(f"missing from {helm_path} (present in {generated_path}):")
        report.extend(_format(t) for t in sorted(missing))
    if extra:
        report.append(f"extra in {helm_path} (no +kubebuilder:rbac marker produces this):")
        report.extend(_format(t) for t in sorted(extra))
    report.append(
        "Fix: edit the Helm role (it's hand-maintained to keep its "
        "explanatory comments) or the +kubebuilder:rbac markers under "
        "operator/, then re-run `make manifests`."
    )
    sys.exit("\n".join(report))


if __name__ == "__main__":
    main()
