// Code generated by tygo. DO NOT EDIT.
/* eslint-disable */
// Code generated by tygo from api-server/internal/model — DO NOT EDIT.
// Regenerate with `make generate-types` (drift-checked in CI).
import type {
  EnvVar,
  Role,
  Toleration,
  WorkspacePlacement,
  WorkspaceSchedule,
  WorkspaceWorkload,
} from './types.manual';

//////////
// source: model.go
/*
Package model holds the platform's persisted and API-facing entities.
*/

/**
 * UserPreferences is the user-owned UI settings blob (JSON column).
 */
export interface UserPreferences {
  /**
   * OpenWorkspaceInNewTab: nil means "never asked" — the portal shows
   * the choice dialog on first open and persists the answer.
   */
  openWorkspaceInNewTab?: boolean;
  /**
   * Language is the preferred UI locale (e.g. "en", "fr").
   */
  language?: string;
  /**
   * Theme is "light" or "dark"; empty follows the system preference.
   */
  theme?: string;
  /**
   * WorkspaceFolders maps workspace ID → folder name, the user's own
   * portal grouping ("infra", "dev", ...). Purely presentational.
   */
  workspaceFolders?: { [key: string]: string };
  /**
   * WorkspaceSettings stores per-workspace connection choices; the
   * server still validates them against the template at connect time.
   */
  workspaceSettings?: { [key: string]: WorkspaceConnectionPrefs };
}
/**
 * WorkspaceConnectionPrefs is the user's saved connection tuning for one
 * workspace: preferred protocol and guacd parameter overrides.
 */
export interface WorkspaceConnectionPrefs {
  protocol?: string;
  /**
   * Params are the overrides of the CHOSEN protocol — what the
   * connect call sends.
   */
  params?: { [key: string]: string };
  /**
   * ParamsByProtocol keeps the overrides per protocol, so the settings
   * tabs round-trip values for protocols other than the chosen one
   * (quick-switching restores them). Without this field here, the
   * PATCH /me unmarshal silently dropped what the frontend saved.
   */
  paramsByProtocol?: { [key: string]: { [key: string]: string } };
}
/**
 * User is a platform account (local auth).
 */
export interface User {
  id: string;
  username: string;
  displayName?: string;
  email?: string;
  role: Role;
  active: boolean;
  maxWorkspaces: number /* int */;
  createdAt: string /* RFC3339 */;
  updatedAt: string /* RFC3339 */;
  lastLoginAt?: string /* RFC3339 */;
  /**
   * Groups mirrors the IdP OIDC groups claim: admin-editable
   * until SSO login refreshes it automatically. Drives WorkspacePolicy
   * and WorkspaceImage group matching.
   */
  groups?: string[];
  /**
   * Preferences is self-service UI state, editable via PATCH /me.
   */
  preferences: UserPreferences;
}
/**
 * SessionKind says what a session's WorkspaceID points at.
 */
export const SessionKindWorkspace = 'workspace'; // provisioned Workspace CR (UID)
/**
 * SessionKind says what a session's WorkspaceID points at.
 */
export const SessionKindRemote = 'remote'; // RemoteWorkspace row (ID)
/**
 * Session records one desktop connection through the proxy.
 */
export interface Session {
  id: string;
  userId: string;
  workspaceId: string;
  workspaceName: string;
  protocol: string;
  clientIp?: string;
  startedAt: string /* RFC3339 */;
  endedAt?: string /* RFC3339 */;
  /**
   * Params are the user's connect-time guacd parameter overrides,
   * already validated against the template's userParams allow-list.
   */
  params?: { [key: string]: string };
  /**
   * Kind distinguishes provisioned-workspace sessions from remote-
   * workspace sessions (empty = workspace, for pre-migration rows).
   */
  kind?: string;
}
/**
 * RemoteWorkspace is a user-registered machine OUTSIDE the cluster,
 * reachable through guacd. It shares nothing with provisioned
 * workspaces: no template, no operator lifecycle, no compute. The
 * credentials live in the Kubernetes Secret named SecretName (one per
 * row), never in the database or this struct.
 * RemoteProtocol is one endpoint a remote machine serves — the same
 * shape the frontend already consumes for provisioned workspaces
 * (name/port/default), so cards, forms and the protocol switch treat
 * both kinds identically.
 */
export interface RemoteProtocol {
  name: string;
  port: number /* int32 */;
  /**
   * Default marks the protocol used when the user picks none.
   */
  default?: boolean;
  /**
   * Params are guacd parameters for THIS protocol (registry-gated).
   */
  params?: { [key: string]: string };
}
export interface RemoteWorkspace {
  id: string;
  ownerId: string;
  name: string;
  hostname: string;
  /**
   * Port/Protocol/Params mirror the DEFAULT entry of Protocols — kept
   * for API and storage compatibility with single-protocol clients.
   */
  port: number /* int32 */;
  protocol: string;
  /**
   * Protocols are every endpoint the machine serves. Empty on legacy
   * rows: EffectiveProtocols synthesizes the single legacy entry.
   */
  protocols?: RemoteProtocol[];
  /**
   * MACAddress enables Wake-on-LAN when set (canonical lower-case,
   * colon-separated). Empty = no WoL.
   */
  macAddress?: string;
  /**
   * Params are guacd connection parameters, validated against the
   * platform registry (non-platform tiers only).
   */
  params?: { [key: string]: string };
  /**
   * CredentialKeys lists which credential fields are stored
   * (username/password/private-key/passphrase), so the UI can display
   * "credentials stored" without any Secret access.
   */
  credentialKeys?: string[];
  createdAt: string /* RFC3339 */;
  updatedAt: string /* RFC3339 */;
}
/**
 * AuditLog is one append-only audit trail entry.
 */
export interface AuditLog {
  id: string;
  occurredAt: string /* RFC3339 */;
  actorId?: string;
  actorUsername?: string;
  action: string;
  resourceType: string;
  resourceId?: string;
  detail?: string;
  clientIp?: string;
}
/**
 * Workspace is the API projection of a Workspace CR.
 */
export interface Workspace {
  id: string;
  name: string;
  displayName?: string;
  templateRef: string;
  ownerId: string;
  /**
   * OwnerUsername is resolved for admin listings only (the fleet view
   * groups by owner); best-effort — empty when the owner is gone.
   */
  ownerUsername?: string;
  phase: string;
  os?: string;
  protocol?: string;
  paused: boolean;
  message?: string;
  createdAt: string /* RFC3339 */;
  /**
   * Namespace is where the workloads run (empty = platform namespace)
   * and WorkloadName the frozen Deployment/Service name — display-only.
   */
  namespace?: string;
  workloadName?: string;
  /**
   * Protocols the workspace serves, with the user-tunable guacd
   * parameter names per protocol (resolved from the template).
   */
  protocols?: WorkspaceProtocol[];
  /**
   * Schedule is the effective uptime/downtime schedule (override or
   * template), so the UI can show and edit it.
   */
  schedule?: WorkspaceSchedule;
  /**
   * NextTransition is the next planned lifecycle change (from status).
   */
  nextTransition?: ScheduledTransition;
  /**
   * TemplateDrifted: the template changed since this workspace's
   * workload was built; the new shape applies at the next resume
   * (docs/adr/0001) — the card shows a "will restart with updates"
   * notice.
   */
  templateDrifted?: boolean;
  /**
   * HomeVolume describes the user-state volume, for the deletion
   * dialog ("volume X (10Gi) will be deleted — keep it?").
   */
  homeVolume?: HomeVolumeInfo;
  /**
   * Runtime is the workspace's CURRENT admitted deviations (env,
   * placement, sizing) — what the runtime settings tab edits through
   * PATCH /workspaces/{id}/overrides.
   */
  runtime?: WorkspaceRuntime;
}
/**
 * WorkspaceRuntime mirrors the workspace's runtime-reconfigurable
 * overrides. PATCH /workspaces/{id}/overrides replaces each PROVIDED
 * field wholesale; the change reaches the live desktop at the next
 * scale-up boundary or on manual reload (docs/adr/0001).
 */
export interface WorkspaceRuntime {
  env?: EnvVar[];
  nodeSelector?: { [key: string]: string };
  tolerations?: Toleration[];
  /**
   * Resources is the user-chosen sizing ({"cpu","memory"} quantities),
   * empty when the template sizing applies.
   */
  resources?: { [key: string]: string };
}
/**
 * HomeVolumeInfo is the display projection of a workspace's home volume.
 */
export interface HomeVolumeInfo {
  name: string;
  size?: string;
}
/**
 * RetainedVolume is a home volume kept from a deleted workspace: still
 * the user's property, still counted against their storage quota, until
 * deleted or reattached to a new workspace.
 */
export interface RetainedVolume {
  name: string;
  namespace: string;
  size: string;
  ownerId: string;
  /**
   * OwnerUsername is resolved for admin listings only (the fleet view
   * groups by owner); best-effort — empty when the owner is gone.
   */
  ownerUsername?: string;
  originWorkspace?: string;
  retainedAt?: string /* RFC3339 */;
}
/**
 * ScheduledTransition is the next planned up/down change of a workspace.
 */
export interface ScheduledTransition {
  time: string /* RFC3339 */;
  up: boolean;
}
/**
 * RemoteWorkspaceAdmin is one row of the admin fleet's remote-workspaces
 * tab: metadata + owner + last connection (never credentials).
 */
export interface RemoteWorkspaceAdmin {
  id: string;
  ownerId: string;
  ownerUsername?: string;
  name: string;
  hostname: string;
  port: number /* int32 */;
  protocol: string;
  macAddress?: string;
  hasCredentials: boolean;
  lastConnectedAt?: string /* RFC3339 */;
  activeNow: boolean;
  createdAt: string /* RFC3339 */;
}
/**
 * WorkspaceProtocol is one connection option of a workspace.
 */
export interface WorkspaceProtocol {
  name: string;
  port?: number /* int32 */;
  default?: boolean;
  /**
   * Params are the template's locked guacd parameters (template views
   * only; workspace listings omit them).
   */
  params?: { [key: string]: string };
  /**
   * UserParams is the template's connect-time delegation list AS
   * CONFIGURED: exact parameter names and/or cat: category selectors
   * (cat:audio). The template editor edits this raw list — cat: intact,
   * so it can tell a category delegated wholesale from names picked
   * one by one.
   */
  userParams?: string[];
  /**
   * ResolvedUserParams is UserParams expanded server-side against the
   * parameter registry into the flat set of names actually overridable
   * at connect time (cat: selectors resolved, platform tier excluded).
   * Connect-time forms consume THIS list — the frontend never parses
   * cat: syntax itself.
   */
  resolvedUserParams?: string[];
  /**
   * CredentialsSecretRef names the credentials Secret (reference only,
   * never its content).
   */
  credentialsSecretRef?: string;
  /**
   * ExposeAudioPort: the template opens the workspace's PulseAudio
   * port (4713) on the pod and Service, so guacd's enable-audio
   * parameter actually reaches an audio server (vnc only).
   */
  exposeAudioPort?: boolean;
}
/**
 * WorkspaceTemplate is the API projection of a WorkspaceTemplate CR.
 */
export interface WorkspaceTemplate {
  id: string;
  name: string;
  displayName: string;
  description?: string;
  /**
   * Logo is the template's icon reference (https URL, `file:<path>`,
   * or dashboard-icons slug); empty falls back to the matching
   * catalog entry's icon, then the OS icon.
   */
  logo?: string;
  os: string;
  image: string;
  port?: number /* int32 */;
  homeSize?: string;
  /**
   * HomeMountPath is where the home volume is mounted (default
   * /home/waas_user; kasmweb images expect /home/kasm-user).
   */
  homeMountPath?: string;
  /**
   * KasmVNCConfig is the admin's ~/.vnc/kasmvnc.yaml content, merged
   * key-by-key over the image's own defaults by KasmVNC (unspecified
   * keys inherit the image default) and mounted read-only in the
   * workspace. The clipboard DLP keys are policy-owned and rejected
   * here — see https://kasmweb.com/kasmvnc/docs/latest/configuration.html
   */
  kasmvncConfig?: string;
  requests?: { [key: string]: string };
  limits?: { [key: string]: string };
  createdAt: string /* RFC3339 */;
  /**
   * Workload is the workload kind stamping desktops (Deployment,
   * StatefulSet or Pod).
   */
  workload?: string;
  /**
   * WorkloadSpec is the CR's workload block verbatim (pod-spec
   * passthrough), for the template editor's advanced section.
   */
  workloadSpec?: WorkspaceWorkload;
  /**
   * Env is the CR's env verbatim (valueFrom included) so the editor can
   * round-trip it. Secret VALUES never appear here — only references.
   */
  env?: EnvVar[];
  /**
   * StorageClassName of the home volume, when pinned.
   */
  storageClassName?: string;
  /**
   * Protocols the template declares (or the OS-derived legacy one).
   */
  protocols?: WorkspaceProtocol[];
  /**
   * AllowedOverrides are the template fields plain users may override
   * at instantiation.
   */
  allowedOverrides?: string[];
  /**
   * OverridesOwner is the username owning this template (may override
   * everything on workspaces stamped from it).
   */
  overridesOwner?: string;
  /**
   * Schedule is the CR's uptime/downtime schedule verbatim.
   */
  schedule?: WorkspaceSchedule;
  /**
   * Placement is the CR's placement block verbatim (target-namespace
   * pattern, namespace metadata, cleanup policy).
   */
  placement?: WorkspacePlacement;
}
/**
 * CatalogImage is the API projection of a WorkspaceImage CR, already
 * filtered down to what the requesting user may deploy.
 */
export interface CatalogImage {
  name: string;
  displayName: string;
  description?: string;
  image?: string;
  /**
   * Registry approves every image under this prefix (exclusive with Image).
   */
  registry?: string;
  /**
   * TagPolicy: digest | tag | any (empty = tag).
   */
  tagPolicy?: string;
  /**
   * ImagePullSecretRef names the registry pull-credentials Secret.
   */
  imagePullSecretRef?: string;
  protocols?: string[];
  architectures?: string[];
  enabled: boolean;
  allowedGroups?: string[];
  defaults?: { [key: string]: string };
  min?: { [key: string]: string };
  max?: { [key: string]: string };
  /**
   * Templates using this image, so the portal can go straight from
   * catalog card to "create workspace".
   */
  templates?: string[];
  /**
   * Discovered are the entries of the last catalog sync
   * (WorkspaceImage.status.catalog) of a registry-mode entry —
   * display metadata (os/app/version/icon) for the picker, nested
   * here (not a root-level list) because each picker card needs both
   * the discovered entry AND the parent's bounds/protocols without
   * re-correlating two lists. Same visibility gate as the rest of
   * the CatalogImage: policy.AllowedImages, nothing extra.
   */
  discovered?: DiscoveredImage[];
}
/**
 * DiscoveredImage is one catalog-sync entry of a registry-mode
 * WorkspaceImage — display metadata only, never an approval.
 */
export interface DiscoveredImage {
  /**
   * Image is the exact, pinned reference (digest recommended).
   */
  image: string;
  /**
   * OS is "linux" or "windows"; empty renders as linux.
   */
  os?: string;
  /**
   * App is a logical grouping slug (e.g. "firefox").
   */
  app?: string;
  version?: string;
  /**
   * Icon is an icon reference (https URL, `file:<path>`, or a
   * dashboard-icons slug fetched live from the CDN — see
   * docs/image-catalog.md); malformed or absent falls back to the
   * OS icon.
   */
  icon?: string;
  displayName?: string;
  /**
   * Profile is a display badge ("hardened"/"normal"); empty shows no
   * badge.
   */
  profile?: string;
  /**
   * Architectures this exact image is published for (amd64/arm64) —
   * per image, unlike the parent CatalogImage.Architectures. Drives
   * the template form's nodeSelector prefill (kubernetes.io/arch when
   * exactly one is listed); empty = unknown, the parent's list is the
   * fallback hint.
   */
  architectures?: string[];
  /**
   * Recommended is an optional deployment-prefill hint the admin
   * template form may copy into a Workload on explicit request —
   * never applied automatically, never enforced. Deliberately its
   * own type rather than shared/catalog.Recommendation: this is the
   * api-server/frontend wire contract (tygo-generated), the other is
   * the inter-repo catalog.yaml contract — two different
   * compatibility cadences, same split as DiscoveredImage vs
   * shared/catalog.Entry.
   */
  recommended?: DeploymentRecommendation;
}
/**
 * DeploymentRecommendation mirrors shared/catalog.Recommendation for
 * the api-server/frontend wire contract. See DiscoveredImage.Recommended.
 */
export interface DeploymentRecommendation {
  podSecurityContext?: unknown;
  securityContext?: unknown;
  volumes?: RecommendedVolume[];
  env?: RecommendedEnvVar[];
}
/**
 * RecommendedVolume mirrors shared/catalog.RecommendedVolume.
 */
export interface RecommendedVolume {
  name: string;
  mountPath: string;
  readOnly?: boolean;
}
/**
 * RecommendedEnvVar mirrors shared/catalog.EnvHint. Protocols stays
 * []string here: there is no CRD Protocol type to reuse on this side,
 * unlike the operator.
 */
export interface RecommendedEnvVar {
  name: string;
  description?: string;
  protocols?: string[];
  requires?: string[];
  default?: string;
}
/**
 * QuotaStatus is "where do I stand" for one user: applied policy, hard
 * limits, and current consumption — everything the portal needs to render
 * "2/3 workspaces, 6 Gi RAM left".
 */
export interface QuotaStatus {
  policy: string;
  policyPriority: number /* int32 */;
  maxWorkspaces?: number /* int32 */;
  usedWorkspaces: number /* int */;
  limits?: { [key: string]: string }; // aggregate caps (cpu/memory/storage)
  used?: { [key: string]: string }; // current aggregates
  perWorkspace?: { [key: string]: string };
  defaults?: { [key: string]: string }; // policy-proposed sizing (image defaults win)
  lifecycle?: { [key: string]: string }; // idleSuspendAfter / maxLifetime
  /**
   * Features flags what the resolved policy opts the user into (e.g.
   * "remoteWorkspaces"); the UI hides gated tabs from it.
   */
  features?: { [key: string]: boolean };
  /**
   * AllowedOverrides is the policy-level override allow-list (nil = the
   * template's own list applies alone).
   */
  allowedOverrides?: string[];
  /**
   * RetainedVolumes/RetainedStorage break down how much of the storage
   * usage comes from volumes kept after workspace deletion (already
   * included in Used["storage"] — display detail, same server-side
   * computation as the enforcement).
   */
  retainedVolumes?: number /* int */;
  retainedStorage?: string;
}
/**
 * PolicyModel is the API projection of a WorkspacePolicy CR for the
 * admin console.
 */
export interface PolicyModel {
  name: string;
  priority: number /* int32 */;
  subjects?: PolicySubject[];
  images?: string[];
  limits: PolicyLimitsModel;
  lifecycle?: { [key: string]: string };
  clipboard?: ClipboardPolicyModel;
  /**
   * Overrides is the policy-level restriction on template overrides
   * (nil = no restriction; empty list = all overrides forbidden).
   */
  overrides?: PolicyOverridesModel;
  /**
   * RemoteWorkspaces opts governed users into the remote workspaces
   * feature.
   */
  remoteWorkspaces?: boolean;
}
/**
 * PolicyOverridesModel mirrors the CRD overrides block.
 */
export interface PolicyOverridesModel {
  /**
   * AllowedFields: the EMPTY list is semantic (every override
   * forbidden) and must serialize as [] — non-nil guaranteed by
   * policyToModel.
   */
  allowedFields: string[];
}
/**
 * ClipboardPolicyModel mirrors the CRD clipboard block (nil = allowed).
 */
export interface ClipboardPolicyModel {
  copyFromWorkspace?: boolean;
  pasteToWorkspace?: boolean;
}
/**
 * PolicySubject mirrors the CRD subject.
 */
export interface PolicySubject {
  kind: string;
  name: string;
}
/**
 * PolicyLimitsModel mirrors the CRD limits in string form.
 */
export interface PolicyLimitsModel {
  maxWorkspaces?: number /* int32 */;
  perWorkspace?: { [key: string]: string };
  aggregate?: { [key: string]: string };
  defaults?: { [key: string]: string };
}
/**
 * EffectivePolicy is the admin debug view answering "which policy governs
 * this user, and why": the resolved identity, every policy with its match
 * outcome, and the winner — computed by the same pkg/policy code the
 * admission webhook runs.
 */
export interface EffectivePolicy {
  userId: string;
  username: string;
  /**
   * Groups: non-nil guaranteed by EffectivePolicyOf's construction.
   */
  groups: string[];
  /**
   * Evaluated lists every policy in resolution order (priority desc).
   * non-nil guaranteed at construction (the report page iterates it
   * unguarded).
   */
  evaluated: EvaluatedPolicy[];
  /**
   * Effective is the winning policy, absent when nothing matches
   * (fail-closed: the user cannot create workspaces at all).
   */
  effective?: PolicyModel;
  warnings?: string[];
  denial?: string;
}
/**
 * EvaluatedPolicy is one policy's outcome during resolution.
 */
export interface EvaluatedPolicy {
  name: string;
  priority: number /* int32 */;
  matched: boolean;
  /**
   * Via is the matching subject ("Group:nymphe:dev", "User:marc") or "*"
   * for a subjects-less catch-all.
   */
  via?: string;
  selected: boolean;
}
/**
 * UserUsage is one row of the admin consumption view.
 */
export interface UserUsage {
  userId: string;
  username?: string;
  groups?: string[];
  policy?: string;
  workspaces: number /* int */;
  used?: { [key: string]: string };
}
/**
 * SessionCapabilities is what the session may do, per clipboard
 * direction; the overlay reflects it, the proxy enforces it. A denied
 * direction carries WHY in its lock field so the overlay can tell an
 * admin policy denial (immutable for the user) from the user's own
 * disable-copy/disable-paste connection setting (undo + reconnect).
 */
export interface SessionCapabilities {
  clipboardCopy: boolean;
  clipboardPaste: boolean;
  /**
   * ClipboardCopyLock/ClipboardPasteLock name the gate that denied the
   * direction: ClipboardLockPolicy or ClipboardLockParams. Empty when
   * the direction is allowed.
   */
  clipboardCopyLock?: ClipboardLock;
  clipboardPasteLock?: ClipboardLock;
}
/**
 * ClipboardLock names the gate that denied a clipboard direction.
 */
export type ClipboardLock = string;
/**
 * ClipboardLockPolicy: the WorkspacePolicy denies the direction (or
 * its resolution failed closed) — not undoable by the user.
 */
export const ClipboardLockPolicy: ClipboardLock = 'policy';
/**
 * ClipboardLockParams: the policy allows it but the session's
 * effective disable-copy/disable-paste param blocks it — the user
 * can re-enable it in the connection settings and reconnect.
 */
export const ClipboardLockParams: ClipboardLock = 'params';
/**
 * WorkspaceEvent is one aggregated Kubernetes Event of a workspace (the
 * CR itself or any managed child resource), pre-authorized server-side.
 */
export interface WorkspaceEvent {
  /**
   * Type is Normal or Warning.
   */
  type: string;
  reason: string;
  message: string;
  objectKind: string;
  objectName: string;
  count: number /* int32 */;
  firstSeen: string /* RFC3339 */;
  lastSeen: string /* RFC3339 */;
}
/**
 * ConnectionInfo is what the WebSocket proxy needs to reach a desktop. It is
 * only ever served on the internal service-to-service endpoint.
 */
export interface ConnectionInfo {
  protocol: string;
  hostname: string;
  port: number /* int32 */;
  password?: string;
  username?: string;
  /**
   * Params are extra guacd connection parameters: the template's locked
   * params merged with the session's user overrides (user wins only on
   * allow-listed names).
   */
  params?: { [key: string]: string };
}
