apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-guacd
  labels:
    app.kubernetes.io/name: waas-guacd
    {{- include "waas.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.guacd.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: waas-guacd
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: waas-guacd
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        seccompProfile: { type: RuntimeDefault }
      containers:
        - name: guacd
          image: {{ .Values.guacd.image | quote }}
          ports:
            - name: guacd
              containerPort: 4822
          livenessProbe:
            tcpSocket: { port: guacd }
            initialDelaySeconds: 10
          readinessProbe:
            tcpSocket: { port: guacd }
            initialDelaySeconds: 5
          securityContext:
            allowPrivilegeEscalation: false
            capabilities: { drop: [ALL] }
          resources:
            {{- toYaml .Values.guacd.resources | nindent 12 }}
